set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}] 
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]

set_property PACKAGE_PIN R14 [get_ports {led_out[0]}] 
set_property PACKAGE_PIN N14 [get_ports {led_out[1]}] 
set_property PACKAGE_PIN V9  [get_ports {led_out[2]}] 
set_property PACKAGE_PIN Y9  [get_ports {led_out[3]}]
set_property PACKAGE_PIN U7  [get_ports {led_out[4]}] 
set_property PACKAGE_PIN V7  [get_ports {led_out[5]}] 
set_property PACKAGE_PIN AB8 [get_ports {led_out[6]}] 
set_property PACKAGE_PIN Y8  [get_ports {led_out[7]}]

set_property PACKAGE_PIN R4 [get_ports sys_clk] 
set_property PACKAGE_PIN U2 [get_ports sys_rst_n] 
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk] 
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]