set_property PACKAGE_PIN G22 [get_ports sys_clk]
set_property PACKAGE_PIN D26 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property PACKAGE_PIN A23 [get_ports {led_out[0]}]
set_property PACKAGE_PIN A24 [get_ports {led_out[1]}]
set_property PACKAGE_PIN D23 [get_ports {led_out[2]}]
set_property PACKAGE_PIN C24 [get_ports {led_out[3]}]
set_property PACKAGE_PIN C26 [get_ports {led_out[4]}]
set_property PACKAGE_PIN D24 [get_ports {led_out[5]}]
set_property PACKAGE_PIN D25 [get_ports {led_out[6]}]
set_property PACKAGE_PIN E25 [get_ports {led_out[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE Yes [current_design]

# autogenerate from vivado tool
set_property MARK_DEBUG true [get_nets {led_out_OBUF[0]}]
set_property MARK_DEBUG true [get_nets {led_out_OBUF[1]}]
set_property MARK_DEBUG true [get_nets {led_out_OBUF[2]}]
set_property MARK_DEBUG true [get_nets {led_out_OBUF[3]}]
set_property MARK_DEBUG true [get_nets {led_out_OBUF[4]}]
set_property MARK_DEBUG true [get_nets {led_out_OBUF[5]}]
set_property MARK_DEBUG true [get_nets {led_out_OBUF[6]}]
set_property MARK_DEBUG true [get_nets {led_out_OBUF[7]}]
set_property MARK_DEBUG true [get_nets sys_rst_n_IBUF]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {led_out_OBUF[0]} {led_out_OBUF[1]} {led_out_OBUF[2]} {led_out_OBUF[3]} {led_out_OBUF[4]} {led_out_OBUF[5]} {led_out_OBUF[6]} {led_out_OBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list sys_clk_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list sys_rst_n_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clk_IBUF_BUFG]
