#--------------------------------------------------------
# synplify test example
#
all:
	synplify_premier syn_directives.prj &

clean:
	rm -rf stdout.* synlog.* rev_*

#--------------------------------------------------------
